<?php
require_once __DIR__.'/../includes/bootstrap.php';require_auth();$db=Database::connection();
$kpis=['clients'=>(int)$db->query("SELECT COUNT(*) FROM clients WHERE statut<>'inactif'")->fetchColumn(),'demandes'=>(int)$db->query("SELECT COUNT(*) FROM demandes_devis WHERE date_demande>=DATE_FORMAT(CURRENT_DATE,'%Y-%m-01')")->fetchColumn(),'contrats'=>(int)$db->query("SELECT COUNT(*) FROM contrats WHERE statut='actif'")->fetchColumn(),'primes'=>(float)$db->query("SELECT COALESCE(SUM(prime_annuelle),0) FROM contrats WHERE statut='actif'")->fetchColumn(),'commissions'=>(float)$db->query("SELECT COALESCE(SUM(montant),0) FROM commissions WHERE statut<>'annulee'")->fetchColumn(),'sinistres'=>(int)$db->query("SELECT COUNT(*) FROM sinistres WHERE statut NOT IN ('refuse','clos')")->fetchColumn()];
$monthly=$db->query("SELECT DATE_FORMAT(date_demande,'%Y-%m') mois,COUNT(*) demandes FROM demandes_devis WHERE date_demande>=DATE_SUB(CURRENT_DATE,INTERVAL 5 MONTH) GROUP BY mois ORDER BY mois")->fetchAll();$branches=$db->query("SELECT cr.libelle,COUNT(*) total FROM contrats c JOIN souscriptions s ON s.id=c.souscription_id JOIN offres_devis o ON o.id=s.offre_id JOIN produits_assurance p ON p.id=o.produit_id JOIN categories_risque cr ON cr.id=p.categorie_id GROUP BY cr.id,cr.libelle")->fetchAll();$expiring=$db->query("SELECT numero_police,date_echeance,DATEDIFF(date_echeance,CURRENT_DATE) jours FROM contrats WHERE statut='actif' AND date_echeance BETWEEN CURRENT_DATE AND DATE_ADD(CURRENT_DATE,INTERVAL 60 DAY) ORDER BY date_echeance LIMIT 8")->fetchAll();$quotes=(int)$db->query('SELECT COUNT(*) FROM demandes_devis')->fetchColumn();$converted=(int)$db->query("SELECT COUNT(*) FROM demandes_devis WHERE statut='convertie'")->fetchColumn();$rate=$quotes?round($converted*100/$quotes,1):0;
$title='Tableau de bord';require __DIR__.'/../includes/header.php';?>
<div class="page-heading"><div><h1 class="h3">Tableau de bord avancé</h1><p class="text-secondary">Pilotage commercial et opérationnel en temps réel</p></div><a class="btn btn-primary" href="<?= APP_URL ?>/demandes/form.php">+ Nouvelle demande</a></div><div class="row g-3"><?php foreach([['Clients actifs',$kpis['clients']],['Demandes du mois',$kpis['demandes']],['Contrats actifs',$kpis['contrats']],['Primes actives',number_format($kpis['primes'],0,',',' ').' F'],['Commissions',number_format($kpis['commissions'],0,',',' ').' F'],['Sinistres ouverts',$kpis['sinistres']]] as $k): ?><div class="col-6 col-xl-2"><div class="card kpi-card h-100"><div class="card-body"><div class="small text-secondary text-uppercase"><?= e($k[0]) ?></div><div class="fs-3 fw-bold mt-2"><?= e((string)$k[1]) ?></div></div></div></div><?php endforeach ?></div>
<div class="row g-3 mt-1"><div class="col-lg-7"><div class="card card-body h-100"><h2 class="h5">Demandes sur six mois</h2><div class="chart-box"><canvas id="monthlyChart"></canvas></div></div></div><div class="col-lg-5"><div class="card card-body h-100"><h2 class="h5">Contrats par branche</h2><div class="chart-box"><canvas id="branchChart"></canvas></div></div></div></div>
<div class="row g-3 mt-1"><div class="col-lg-5"><div class="card card-body"><h2 class="h5">Performance commerciale</h2><div class="display-5 fw-bold text-primary"><?= $rate ?> %</div><p class="text-secondary">Taux de transformation demandes → contrats</p><div class="progress"><div class="progress-bar" style="width:<?= min(100,$rate) ?>%"></div></div></div></div><div class="col-lg-7"><div class="card"><div class="card-body"><h2 class="h5">Échéances dans les 60 jours</h2></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Police</th><th>Échéance</th><th>Délai</th></tr></thead><tbody><?php foreach($expiring as $r): ?><tr><td><?= e($r['numero_police']) ?></td><td><?= date('d/m/Y',strtotime($r['date_echeance'])) ?></td><td><span class="badge text-bg-warning"><?= (int)$r['jours'] ?> jour(s)</span></td></tr><?php endforeach ?><?php if(!$expiring): ?><tr><td colspan="3" class="text-center text-secondary">Aucune échéance proche.</td></tr><?php endif ?></tbody></table></div></div></div></div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>document.addEventListener('DOMContentLoaded',()=>{const monthly=<?= json_encode($monthly,JSON_UNESCAPED_UNICODE) ?>,branches=<?= json_encode($branches,JSON_UNESCAPED_UNICODE) ?>;new Chart(document.getElementById('monthlyChart'),{type:'line',data:{labels:monthly.map(x=>x.mois),datasets:[{label:'Demandes',data:monthly.map(x=>x.demandes),borderColor:'#2f6fae',backgroundColor:'rgba(47,111,174,.15)',fill:true,tension:.35}]},options:{responsive:true,maintainAspectRatio:false}});new Chart(document.getElementById('branchChart'),{type:'doughnut',data:{labels:branches.map(x=>x.libelle),datasets:[{data:branches.map(x=>x.total),backgroundColor:['#17345f','#2f6fae','#d4a72c']}]},options:{responsive:true,maintainAspectRatio:false}})});</script>
<?php require __DIR__.'/../includes/footer.php'; ?>
