<?php
require_once __DIR__.'/../../includes/bootstrap.php'; require_roles(['ADMIN','RESPONSABLE','AGENT']);
$db=Database::connection();$q=trim((string)($_GET['q']??''));$statut=(string)($_GET['statut']??'');$page=max(1,(int)($_GET['page']??1));$per=20;$w=[];$p=[];
if($q!==''){$w[]='(code LIKE :q OR raison_sociale LIKE :q OR contact_commercial LIKE :q)';$p['q']='%'.$q.'%';}if(in_array($statut,['active','inactive'],true)){$w[]='statut=:statut';$p['statut']=$statut;}$where=$w?' WHERE '.implode(' AND ',$w):'';
$s=$db->prepare('SELECT COUNT(*) FROM compagnies'.$where);$s->execute($p);$total=(int)$s->fetchColumn();$pages=max(1,(int)ceil($total/$per));$page=min($page,$pages);$s=$db->prepare('SELECT c.*,(SELECT COUNT(*) FROM produits_assurance p WHERE p.compagnie_id=c.id) nb_produits FROM compagnies c'.$where.' ORDER BY raison_sociale LIMIT :lim OFFSET :off');foreach($p as $k=>$v)$s->bindValue(':'.$k,$v);$s->bindValue(':lim',$per,PDO::PARAM_INT);$s->bindValue(':off',($page-1)*$per,PDO::PARAM_INT);$s->execute();$rows=$s->fetchAll();$title='Compagnies';require __DIR__.'/../../includes/header.php';
?>
<div class="page-heading"><div><h1 class="h3">Compagnies partenaires</h1><p class="text-secondary"><?= $total ?> compagnie(s)</p></div><a class="btn btn-primary" href="form.php">+ Nouvelle compagnie</a></div>
<form class="filter-bar" method="get"><input class="form-control" name="q" value="<?= e($q) ?>" placeholder="Code, compagnie ou contact"><select class="form-select" name="statut"><option value="">Tous les statuts</option><option value="active" <?= $statut==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= $statut==='inactive'?'selected':'' ?>>Inactive</option></select><button class="btn btn-dark">Rechercher</button></form>
<div class="card"><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Code</th><th>Compagnie</th><th>Contact</th><th>Produits</th><th>Statut</th><th class="text-end">Actions</th></tr></thead><tbody><?php foreach($rows as $r): ?><tr><td class="fw-semibold"><?= e($r['code']) ?></td><td><?= e($r['raison_sociale']) ?><div class="small text-secondary"><?= e($r['adresse']) ?></div></td><td><?= e($r['contact_commercial']) ?><div class="small"><?= e($r['telephone']) ?></div></td><td><?= (int)$r['nb_produits'] ?></td><td><span class="badge text-bg-<?= $r['statut']==='active'?'success':'secondary' ?>"><?= e($r['statut']) ?></span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary" href="form.php?id=<?= (int)$r['id'] ?>">Modifier</a> <form class="d-inline" method="post" action="delete.php" data-confirm="Supprimer cette compagnie ?"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="btn btn-sm btn-outline-danger">Supprimer</button></form></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="6" class="empty-state">Aucune compagnie trouvée.</td></tr><?php endif; ?></tbody></table></div></div>
<?php if($pages>1): ?><nav class="mt-3"><ul class="pagination"><?php for($i=1;$i<=$pages;$i++): ?><li class="page-item <?= $i===$page?'active':'' ?>"><a class="page-link" href="?<?= http_build_query(['q'=>$q,'statut'=>$statut,'page'=>$i]) ?>"><?= $i ?></a></li><?php endfor ?></ul></nav><?php endif; require __DIR__.'/../../includes/footer.php'; ?>
